[project]
name = "shortrocity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gtts>=2.5.4",
    "moviepy>=2.1.2",
    "streamlit>=1.45.1",
]
